export const SET_NGUOI_DUNG = 'SET_NGUOI_DUNG';

export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG';
export const XOA_NGUOI_DUNG = 'XOA_NGUOI_DUNG';
export const CAP_NHAT_NGUOI_DUNG = 'CAP_NHAT_NGUOI_DUNG';
export const CHINH_SUA_NGUOI_DUNG = 'CHINH_SUA_NGUOI_DUNG'